<?php
/**
 * Implements hook_install().
 */
function campuscms_feature_page_install() {
  if (module_exists('custom_breadcrumbs')) {
    _campuscms_feature_page_custom_breadcrumbs();
  }
}

/**
 * Implements hook_uninstall().
 */
function campuscms_feature_page_uninstall() {
  if (module_exists('custom_breadcrumbs')) {
    db_delete('custom_breadcrumbs')->condition('name', 'campuscms_feature_page-%', 'LIKE')->execute();
  }
}
